services:
  seismopattern:
    build:
      context: .
      dockerfile: Dockerfile
    image: seismopattern:stable
    pull_policy: never
    container_name: seismopattern_app
    working_dir: /app
    command: ["python", "app.py"]
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    restart: unless-stopped
