#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from pathlib import Path

ROOT = Path(".")
DOCS = Path("docs")
DOCS.mkdir(exist_ok=True)


def w(path, content):
    p = Path(path)
    p.write_text(content.strip() + "\n", encoding="utf-8")
    lines = len(content.splitlines())
    print(f"Yazildi: {p} ({lines} satir)")


README = (
    "# SeismoPattern\n\n"
    "Kalibrated, cok katmanli, segment olcekli, olasiliksal deprem risk izleme sistemi.\n\n"
    "**Deterministik deprem zaman tahmini degildir.**\n\n"
    "---\n\n"
    "## Sistem Nedir\n\n"
    "SeismoPattern, dunya genelinde buyuk depremlerin (Mw 7.0+) oncesinde\n"
    "gozlemlenen sismik oruntuleri tespit eden bir risk izleme sistemidir.\n\n"
    "Sistem sunlari yapar:\n\n"
    "- Segment olcekli uzun vadeli tehlike degerlendirmesi\n"
    "- Kisa vadeli sismik anomali tespiti\n"
    "- Cok katmanli risk skoru uretimi\n"
    "- Olasiliksal horizon bazli tehlike hesabi\n\n"
    "Sistem sunlari yapmaz:\n\n"
    "- Belirli bir tarihte deprem olacagini soylememez\n"
    "- Kesin uyari vermez\n"
    "- Resmi erken uyari sisteminin yerini tutmaz\n\n"
    "---\n\n"
    "## Model Performans Metrikleri\n\n"
    "OOS AUC-ROC (5-fold CV)   : 0.7054  CI: 0.6788 - 0.7330\n"
    "PR-AUC                    : 0.9101\n"
    "Brier Score               : 0.1791\n"
    "ECE (isotonic sonrasi)    : 0.0181\n"
    "Debiased benchmark AUC    : 0.9219\n"
    "DeLong testi              : 6/6 baseline p<0.05\n\n"
    "---\n\n"
    "## Veri Kaynaklari\n\n"
    "GCMT      : 1976-2025 deprem katalogu     (69944 olay)\n"
    "ISC FDSN  : Canli bolgesel sismisitesi    (API)\n"
    "USGS FDSN : Canli yedek kaynak            (API)\n"
    "GEM       : Aktif fay segmentleri         (16195 segment)\n"
    "MIDAS     : GPS hiz veritabani            (20168 istasyon)\n\n"
    "---\n\n"
    "## Hizli Baslangic\n\n"
    "Docker ile:\n\n"
    "    docker compose -f docker-compose.runtime.yml up\n\n"
    "Yerel Python ile:\n\n"
    "    python -m venv venv\n"
    "    venv\\Scripts\\activate\n"
    "    pip install -r requirements.txt\n"
    "    pip install --no-deps xgboost==3.3.0\n"
    "    python app.py\n\n"
    "Web arayuzu : http://127.0.0.1:5000\n"
    "API docs    : http://127.0.0.1:5000/docs\n\n"
    "---\n\n"
    "## API Endpoint Ornekleri\n\n"
    "    GET  /api/status          sistem durumu\n"
    "    POST /api/realtime        canli bolge analizi\n"
    "    GET  /api/dual_risk       dual risk framework\n"
    "    GET  /api/hazard_table    25 bolge hazard tablosu\n"
    "    GET  /api/hazard          horizon bazli tehlike\n"
    "    GET  /api/geodynamic      tum katmanlar birlesik\n"
    "    GET  /api/pdf             PDF rapor\n"
    "    GET  /docs                Swagger UI\n\n"
    "---\n\n"
    "## Prospective Dogrulama\n\n"
    "15 Temmuz 2026 tarihinden itibaren haftalik immutable tahmin kaydi yapilmaktadir.\n\n"
    "Her tahmin SHA-256 ile hashlenip JSON arsive yazilir.\n"
    "SQLite trigger ile degistirilemez hale getirilir.\n"
    "Hash zinciri ile onceki kayitlara baglanir.\n\n"
    "Ilk degerlendirme: Ekim 2026 (90 gun penceresi)\n\n"
    "    python scripts/prospective_tracker.py --record\n"
    "    python scripts/prospective_tracker.py --verify\n"
    "    python scripts/prospective_tracker.py --status\n\n"
    "---\n\n"
    "## Bilimsel Belgeler\n\n"
    "    docs/Limitations.md              sistem sinirlamalari\n"
    "    docs/Scientific_Methodology.md   bilimsel metodoloji\n"
    "    docs/Validation_Methodology.md   dogrulama yaklasimi\n"
    "    docs/Feature_Definitions.md      feature tanimlari\n"
    "    docs/Risk_Model.md               risk modeli\n"
    "    docs/Calibration.md              kalibrasyon\n"
    "    docs/DEPLOYMENT.md               kurulum ve calistirma\n\n"
    "---\n\n"
    "## Onemli Uyari\n\n"
    "Bu sistem arastirma ve karar destek amaclidir.\n"
    "Tahliye karari, resmi afet yonetimi veya muhendislik standardi\n"
    "belirleme icin tek basina kullanilmamalidir.\n\n"
    "Yuksek risk skoru yakin deprem garantisi degildir.\n"
    "Dusuk risk skoru guvenlik garantisi degildir.\n"
)


DEPLOYMENT = (
    "# SeismoPattern - Kurulum ve Calistirma Kilavuzu\n\n"
    "Guncelleme: Temmuz 2026\n\n"
    "---\n\n"
    "## Gereksinimler\n\n"
    "- Python 3.12+\n"
    "- Docker Desktop (Windows) veya Docker Engine (Linux)\n"
    "- 8 GB RAM onerilir\n"
    "- 10 GB disk alani\n\n"
    "---\n\n"
    "## Yontem 1: Docker ile Calistirma (Onerilen)\n\n"
    "Bu yontem tum bagimlilikları otomatik olarak yonetir.\n\n"
    "Adim 1: Projeyi indirin\n\n"
    "    git clone <repo>\n"
    "    cd SeismoPattern\n\n"
    "Adim 2: Compose ile baslatin\n\n"
    "    docker compose -f docker-compose.runtime.yml up\n\n"
    "Ilk baslangicta pip install yapacagi icin 3-5 dakika surer.\n"
    "Sonraki baslatmalarda paketler zaten kurulu oldugu icin hizlidir.\n\n"
    "Adim 3: Erisim\n\n"
    "    Web arayuzu : http://127.0.0.1:5000\n"
    "    API docs    : http://127.0.0.1:5000/docs\n\n"
    "Arka planda calistirmak icin:\n\n"
    "    docker compose -f docker-compose.runtime.yml up -d\n\n"
    "Durdurmak icin:\n\n"
    "    docker compose -f docker-compose.runtime.yml down\n\n"
    "---\n\n"
    "## Yontem 2: Yerel Python ile Calistirma\n\n"
    "Adim 1: Sanal ortam olusturun\n\n"
    "    python -m venv venv\n"
    "    venv\\Scripts\\activate   (Windows)\n"
    "    source venv/bin/activate  (Linux/Mac)\n\n"
    "Adim 2: Bagimliliklar\n\n"
    "    pip install -r requirements.txt\n"
    "    pip install --no-deps xgboost==3.3.0\n\n"
    "Adim 3: Calistirin\n\n"
    "    python app.py\n\n"
    "---\n\n"
    "## Kalici Docker Image Olusturma\n\n"
    "Ilk basarili calistirma sonrasi container kaydedilebilir:\n\n"
    "    docker commit seismopattern_app seismopattern:stable\n\n"
    "Sonra docker-compose.runtime.yml icinde degistirin:\n\n"
    "    image: seismopattern:stable\n\n"
    "Bu sekilde sonraki baslangiclar pip install atlar (~30 saniye).\n\n"
    "---\n\n"
    "## Bagimlilik Notlari\n\n"
    "Runtime bagimliliklar (requirements.txt):\n\n"
    "    Flask==3.0.3\n"
    "    Werkzeug==3.0.6\n"
    "    pandas, numpy, scipy, requests, matplotlib\n"
    "    scikit-learn, joblib, reportlab, folium\n"
    "    SQLAlchemy, lxml, networkx, shapely\n\n"
    "xgboost ayrica kurulur:\n\n"
    "    pip install --no-deps xgboost==3.3.0\n\n"
    "Egitim bagimlilikları (requirements_train.txt):\n\n"
    "    lightgbm, catboost, imbalanced-learn, shap, torch\n\n"
    "Bu paketler sadece model egitimi icin gereklidir.\n"
    "Runtime API icin gerekmez.\n\n"
    "---\n\n"
    "## Flask/Werkzeug Uyum Notu\n\n"
    "Flask==3.0.3 ve Werkzeug==3.0.6 birlikte kullanilmalidir.\n"
    "Flask==3.1.x ile Werkzeug==3.1.8 kombinasyonu\n"
    "bu sistemde LocalProxy uyumsuzluguna yol acmaktadir.\n\n"
    "---\n\n"
    "## Bilinen Sorunlar\n\n"
    "Docker BuildKit EOF hatasi:\n\n"
    "    docker buildx build --output type=docker,dest=image.tar -t seismopattern:test .\n\n"
    "ISC baglanti gecikmesi:\n\n"
    "    ISC mirror (iris.washington.edu) her zaman basarisiz olur.\n"
    "    Sistem otomatik olarak www.isc.ac.uk adresine gecer.\n"
    "    Ilk sorgu 7-15 saniye surebilir.\n"
    "    Onbellek TTL: 2 saat.\n\n"
    "---\n\n"
    "## Prospective Izleme\n\n"
    "Haftalik tahmin kaydi:\n\n"
    "    python scripts/prospective_tracker.py --record\n"
    "    python scripts/prospective_tracker.py --check-events\n"
    "    python scripts/prospective_tracker.py --verify\n"
    "    python scripts/prospective_tracker.py --status\n\n"
    "Windows Task Scheduler kurulumu projeyle birlikte gelir.\n\n"
    "---\n\n"
    "## API Hizli Basvuru\n\n"
    "    Durum         GET  /api/status\n"
    "    Ana arayuz    GET  /\n"
    "    API docs      GET  /docs\n\n"
    "    Risk analizi  POST /api/realtime\n"
    "                  POST /api/historical\n"
    "                  GET  /api/geodynamic\n\n"
    "    Bolgeler      GET  /api/zones\n"
    "                  GET  /api/dual_risk\n"
    "                  GET  /api/hazard_table\n"
    "                  GET  /api/hazard\n\n"
    "    Fiziksel      GET  /api/faults\n"
    "                  GET  /api/gps\n"
    "                  GET  /api/cff\n\n"
    "    Raporlar      GET  /api/pdf\n"
    "                  GET  /map\n"
)


w("README.md", README)
w("docs/DEPLOYMENT.md", DEPLOYMENT)
print("Tamamlandi.")